apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana

spec: 
  ports:
    - port: 3000
      name: grafana
      nodePort: 32000
  type: NodePort
  selector:
    app: grafana
